-- IJF-ის ოფიციალური კალენდრიდან (ijf.org) წამოღებული საერთაშორისო ტურნირები 2026
insert into events (slug, day, month, date_range, tag, title, location, category, description) values
('casablanca-african-open-2026-ijf', '25', 'იან', '25 იანვარი 2026', 'საერთაშორისო', 'Casablanca African Open 2026', 'მაროკო, კასაბლანკა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('gij-n-kata-world-series-2026-ijf', '25', 'იან', '25 იანვარი 2026', 'საერთაშორისო', 'Gijón Kata World Series 2026', 'ესპანეთი, ხიხონი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('sofia-european-open-2026-ijf', '31', 'იან', '31 იანვარი - 1 თებერვალი 2026', 'საერთაშორისო', 'Sofia European Open 2026', 'ბულგარეთი, სოფია', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('paris-grand-slam-2026-ijf', '7', 'თებ', '7-8 თებერვალი 2026', 'საერთაშორისო', 'Paris Grand Slam 2026', 'საფრანგეთი, პარიზი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('ljubljana-european-open-2026-ijf', '14', 'თებ', '14-15 თებერვალი 2026', 'საერთაშორისო', 'Ljubljana European Open 2026', 'სლოვენია, ლუბლიანა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('tunis-african-open-2026-ijf', '15', 'თებ', '15 თებერვალი 2026', 'საერთაშორისო', 'Tunis African Open 2026', 'ტუნისი, ტუნისი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('otp-group-tashkent-grand-slam-2026-ijf', '27', 'თებ', '27 თებერვალი - 1 მარტი 2026', 'საერთაშორისო', 'OTP Group Tashkent Grand Slam 2026', 'უზბეკეთი, ტაშკენტი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('grand-prix-upper-austria-2026-ijf', '6', 'მარ', '6-8 მარტი 2026', 'საერთაშორისო', 'Grand Prix Upper Austria 2026', 'ავსტრია, ლინცი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('tbilisi-veteran-european-cup-2026-ijf', '7', 'მარ', '7 მარტი 2026', 'საერთაშორისო', 'Tbilisi Veteran European Cup 2026', 'საქართველო, თბილისი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('warsaw-european-open-2026-ijf', '14', 'მარ', '14-15 მარტი 2026', 'საერთაშორისო', 'Warsaw European Open 2026', 'პოლონეთი, ვარშავა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('tbilisi-grand-slam-2026-ijf', '20', 'მარ', '20-22 მარტი 2026', 'საერთაშორისო', 'Tbilisi Grand Slam 2026', 'საქართველო, თბილისი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('tbilisi-itc-2026-ijf', '23', 'მარ', '23-28 მარტი 2026', 'საერთაშორისო', 'Tbilisi ITC 2026', 'საქართველო, თბილისი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('european-senior-championships-2026-individuals-ijf', '16', 'აპრ', '16-19 აპრილი 2026', 'საერთაშორისო', 'European Senior Championships 2026 Individuals', 'საქართველო, თბილისი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('asian-senior-championships-2026-individuals-ijf', '16', 'აპრ', '16-18 აპრილი 2026', 'საერთაშორისო', 'Asian Senior Championships 2026 Individuals', 'ჩინეთი, ორდოსი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('panamerican-senior-championships-2026-individuals-ijf', '18', 'აპრ', '18-19 აპრილი 2026', 'საერთაშორისო', 'Panamerican Senior Championships 2026 Individuals', 'პანამა, პანამა-სითი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('african-senior-championships-2026-individuals-ijf', '24', 'აპრ', '24-25 აპრილი 2026', 'საერთაშორისო', 'African Senior Championships 2026 Individuals', 'კენია, ნაირობი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('dushanbe-grand-slam-2026-ijf', '1', 'მაი', '1-3 მაისი 2026', 'საერთაშორისო', 'Dushanbe Grand Slam 2026', 'ტაჯიკეთი, დუშანბე', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('qazaqstan-barysy-grand-slam-2026-ijf', '8', 'მაი', '8-10 მაისი 2026', 'საერთაშორისო', 'Qazaqstan Barysy Grand Slam 2026', 'ყაზახეთი, ასტანა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('gori-senior-european-cup-2026-ijf', '9', 'მაი', '9-10 მაისი 2026', 'საერთაშორისო', 'Gori Senior European Cup 2026', 'საქართველო, გორი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('european-judo-championships-kata-sarajevo-2026-ijf', '16', 'მაი', '16-17 მაისი 2026', 'საერთაშორისო', 'European Judo Championships Kata Sarajevo 2026', 'ბოსნია და ჰერცეგოვინა, სარაევო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('tallinn-european-open-2026-ijf', '6', 'ივნ', '6-7 ივნისი 2026', 'საერთაშორისო', 'Tallinn European Open 2026', 'ესტონეთი, ტალინი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('ulaanbaatar-grand-slam-2026-ijf', '19', 'ივნ', '19-21 ივნისი 2026', 'საერთაშორისო', 'Ulaanbaatar Grand Slam 2026', 'მონღოლეთი, ულან-ბატორი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('qingdao-grand-prix-2026-ijf', '26', 'ივნ', '26-28 ივნისი 2026', 'საერთაშორისო', 'Qingdao Grand Prix 2026', 'ჩინეთი, ცინგდაო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('prague-european-open-2026-ijf', '27', 'ივნ', '27-28 ივნისი 2026', 'საერთაშორისო', 'Prague European Open 2026', 'ჩეხეთი, პრაღა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('millennium-team-european-championships-cadets-gran-canaria-2026-ijf', '29', 'ივნ', '29 ივნისი - 1 ივლისი 2026', 'საერთაშორისო', 'Millennium Team European Championships Cadets Gran Canaria 2026', 'ესპანეთი, გრან-კანარია', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('sarajevo-european-open-2026-ijf', '18', 'ივლ', '18-19 ივლისი 2026', 'საერთაშორისო', 'Sarajevo European Open 2026', 'ბოსნია და ჰერცეგოვინა, სარაევო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('commonwealth-games-glasgow-2026-ijf', '31', 'ივლ', '31 ივლისი - 2 აგვისტო 2026', 'საერთაშორისო', 'Commonwealth Games Glasgow 2026', 'დიდი ბრიტანეთი, გლაზგო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('lima-grand-prix-2026-ijf', '14', 'აგვ', '14-16 აგვისტო 2026', 'საერთაშორისო', 'Lima Grand Prix 2026', 'პერუ, ლიმა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('guayaquil-world-championships-cadets-2026-ijf', '20', 'აგვ', '20-22 აგვისტო 2026', 'საერთაშორისო', 'Guayaquil World Championships Cadets 2026', 'ეკვადორი, გუაიაკილი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('lausanne-grand-slam-2026-ijf', '28', 'აგვ', '28-30 აგვისტო 2026', 'საერთაშორისო', 'Lausanne Grand Slam 2026', 'შვეიცარია, ლოზანა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('xx-mediterranean-games-2026-ijf', '28', 'აგვ', '28-29 აგვისტო 2026', 'საერთაშორისო', 'XX Mediterranean Games 2026', 'იტალია, ტარანტო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('european-championships-juniors-podgorica-2026-ijf', '3', 'სექ', '3-5 სექტემბერი 2026', 'საერთაშორისო', 'European Championships Juniors Podgorica 2026', 'მონტენეგრო, პოდგორიცა', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('hungary-grand-slam-2026-ijf', '11', 'სექ', '11-13 სექტემბერი 2026', 'საერთაშორისო', 'Hungary Grand Slam 2026', 'უნგრეთი, ბუდაპეშტი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('sarajevo-world-championships-veterans-2026-ijf', '20', 'სექ', '20-24 სექტემბერი 2026', 'საერთაშორისო', 'Sarajevo World Championships Veterans 2026', 'ბოსნია და ჰერცეგოვინა, სარაევო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('sarajevo-world-championships-kata-2026-ijf', '26', 'სექ', '26-27 სექტემბერი 2026', 'საერთაშორისო', 'Sarajevo World Championships Kata 2026', 'ბოსნია და ჰერცეგოვინა, სარაევო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('baku-world-senior-championships-2026-ijf', '4', 'ოქტ', '4-10 ოქტომბერი 2026', 'საერთაშორისო', 'Baku World Senior Championships 2026', 'აზერბაიჯანი, ბაქო', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('european-championships-veterans-2026-ijf', '22', 'ოქტ', '22-25 ოქტომბერი 2026', 'საერთაშორისო', 'European Championships Veterans 2026', 'პორტუგალია, პორტიმაუ', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org'),
('abu-dhabi-grand-slam-2026-ijf', '29', 'ოქტ', '29-31 ოქტომბერი 2026', 'საერთაშორისო', 'Abu Dhabi Grand Slam 2026', 'არაბთა გაერთიანებული საემიროები, აბუ-დაბი', 'international', 'IJF-ის ოფიციალური კალენდარი — ijf.org')
on conflict (slug) do nothing;

select count(*) as ijf_events_count from events where description like 'IJF%';
